/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth.tsx'
import { Route as ChargeRouteImport } from './routes/charge.tsx'
import { Route as CodesRouteImport } from './routes/codes.tsx'
import { Route as DashboardRouteImport } from './routes/dashboard.tsx'
import { Route as MyCodeRouteImport } from './routes/my-code.tsx'
import { Route as ProductsRouteImport } from './routes/products.tsx'
import { Route as ReportsRouteImport } from './routes/reports.tsx'
import { Route as SettingsRouteImport } from './routes/settings.tsx'
import { Route as TransactionsRouteImport } from './routes/transactions.tsx'
import { Route as WithdrawRouteImport } from './routes/withdraw.tsx'
import { Route as AdminIndexRouteImport } from './routes/admin.index.tsx'
import { Route as AdminAuditRouteImport } from './routes/admin.audit.tsx'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants.tsx'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing.tsx'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers.tsx'
import { Route as AdminSettlementsRouteImport } from './routes/admin.settlements.tsx'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions.tsx'
import { Route as AdminUsersRouteImport } from './routes/admin.users.tsx'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals.tsx'
import { Route as CodesCodeIdRouteImport } from './routes/codes.$codeId.tsx'
import { Route as PayReferenceRouteImport } from './routes/pay.$reference.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChargeRoute = ChargeRouteImport.update({
  id: '/charge',
  path: '/charge',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesRoute = CodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCodeRoute = MyCodeRouteImport.update({
  id: '/my-code',
  path: '/my-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/admin/merchants',
  path: '/admin/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettlementsRoute = AdminSettlementsRouteImport.update({
  id: '/admin/settlements',
  path: '/admin/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const CodesCodeIdRoute = CodesCodeIdRouteImport.update({
  id: '/$codeId',
  path: '/$codeId',
  getParentRoute: () => CodesRoute,
} as any)
const PayReferenceRoute = PayReferenceRouteImport.update({
  id: '/pay/$reference',
  path: '/pay/$reference',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/charge': typeof ChargeRoute
  '/codes': typeof CodesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/my-code': typeof MyCodeRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/codes/$codeId': typeof CodesCodeIdRoute
  '/pay/$reference': typeof PayReferenceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/charge': typeof ChargeRoute
  '/codes': typeof CodesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/my-code': typeof MyCodeRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/codes/$codeId': typeof CodesCodeIdRoute
  '/pay/$reference': typeof PayReferenceRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/charge': typeof ChargeRoute
  '/codes': typeof CodesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/my-code': typeof MyCodeRoute
  '/products': typeof ProductsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/codes/$codeId': typeof CodesCodeIdRoute
  '/pay/$reference': typeof PayReferenceRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/charge'
    | '/codes'
    | '/dashboard'
    | '/my-code'
    | '/products'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/withdraw'
    | '/admin/audit'
    | '/admin/merchants'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/settlements'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/codes/$codeId'
    | '/pay/$reference'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/charge'
    | '/codes'
    | '/dashboard'
    | '/my-code'
    | '/products'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/withdraw'
    | '/admin/audit'
    | '/admin/merchants'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/settlements'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/codes/$codeId'
    | '/pay/$reference'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/charge'
    | '/codes'
    | '/dashboard'
    | '/my-code'
    | '/products'
    | '/reports'
    | '/settings'
    | '/transactions'
    | '/withdraw'
    | '/admin/audit'
    | '/admin/merchants'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/settlements'
    | '/admin/transactions'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/codes/$codeId'
    | '/pay/$reference'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChargeRoute: typeof ChargeRoute
  CodesRoute: typeof CodesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  MyCodeRoute: typeof MyCodeRoute
  ProductsRoute: typeof ProductsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  WithdrawRoute: typeof WithdrawRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminSettlementsRoute: typeof AdminSettlementsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  PayReferenceRoute: typeof PayReferenceRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charge': {
      id: '/charge'
      path: '/charge'
      fullPath: '/charge'
      preLoaderRoute: typeof ChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes': {
      id: '/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof CodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-code': {
      id: '/my-code'
      path: '/my-code'
      fullPath: '/my-code'
      preLoaderRoute: typeof MyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/admin/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settlements': {
      id: '/admin/settlements'
      path: '/admin/settlements'
      fullPath: '/admin/settlements'
      preLoaderRoute: typeof AdminSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codes/$codeId': {
      id: '/codes/$codeId'
      path: '/$codeId'
      fullPath: '/codes/$codeId'
      preLoaderRoute: typeof CodesCodeIdRouteImport
      parentRoute: typeof CodesRoute
    }
    '/pay/$reference': {
      id: '/pay/$reference'
      path: '/pay/$reference'
      fullPath: '/pay/$reference'
      preLoaderRoute: typeof PayReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CodesRouteChildren {
  CodesCodeIdRoute: typeof CodesCodeIdRoute
}

const CodesRouteChildren: CodesRouteChildren = {
  CodesCodeIdRoute: CodesCodeIdRoute,
}

const CodesRouteWithChildren = CodesRoute._addFileChildren(CodesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChargeRoute: ChargeRoute,
  CodesRoute: CodesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  MyCodeRoute: MyCodeRoute,
  ProductsRoute: ProductsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  WithdrawRoute: WithdrawRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminSettlementsRoute: AdminSettlementsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  PayReferenceRoute: PayReferenceRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
